config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'dashboard#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/:adapter/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy'

  resources :contacts
  resources :leads do
    member do
      post :send_email
      post :book_appointment
      post :send_quotation
      get :installation_email
      get :quotation_email
      post :invoice
    end
  end
  resources :employees
  resources :products
  resources :translations, except: [:show]
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :small, resize_to_limit: [400, 400]
  end

  scope :installers, -> { where(job: 'Installer') }
  scope :internal, -> { where(internal: true) }

  validates :name,
            :email,
            :calendar_id,
            :contact_number,
            :job,
            :introduction,
            :preferred_start_time,
            presence: true

  validates_inclusion_of :internal, in: [true, false]

  validates :email, uniqueness: true

  def self.find_by_lowercase_name(name)
    where('lower(name) = ?', name.downcase).first
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_path }
      format.js
    end
  end

  private

  def employee_params
    params.require(:employee).permit(
      :contact_number, :job, :introduction, :name, :email, :calendar_id, :internal, :preferred_start_time, :avatar
    )
  end
end

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
	<div class="form-group">
		<%= form.label :name %>
		<%= form.text_area :name, class: "form-control" %>
		<% employee.errors.full_messages_for(:name).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :email %>
		<%= form.text_area :email, class: "form-control" %>
		<% employee.errors.full_messages_for(:email).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :calendar_id, 'Calendar ID' %>
		<%= form.text_area :calendar_id, class: "form-control" %>
		<% employee.errors.full_messages_for(:calendar_id).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :job %>
		<%= form.text_area :job, class: "form-control" %>
		<% employee.errors.full_messages_for(:job).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :introduction %>
		<%= form.text_area :introduction, class: "form-control" %>
		<% employee.errors.full_messages_for(:introduction).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :contact_number %>
		<%= form.text_area :contact_number, class: "form-control" %>
		<% employee.errors.full_messages_for(:contact_number).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :internal %>
		<%= form.check_box :internal %>
		<% employee.errors.full_messages_for(:internal).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :preferred_start_time %>
		<%= form.time_field :preferred_start_time, value: '08:00', class: "form-control" %>
		<% employee.errors.full_messages_for(:preferred_start_time).each do |message| %>
			<div><%= message %></div>
		<% end %>
    </div>

	<div class="form-group">
		<%= form.label :avatar, 'Picture' %>
		<%= form.file_field :avatar, class: "form-control" %>
		<% employee.errors.full_messages_for(:avatar).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.submit :class => "btn btn-primary float-end" %>
	</div>
<% end %>

app/views/employees/destroy.js.erb
document.querySelector("#employee_" + <%= @employee.id %>).remove();

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<div class="container-fluid">
  <h1>Employees</h1>

  <hr/>

  <div class="button-wrap">
    <%= button_to "Add New Employee", new_employee_path, method: :get, class: "btn btn-primary" %>
  </div>

  <% @employees.each do |employee| %>
    <div class="card mb-3" id="employee_<%= employee.id %>">
      <div class="row g-0">
        <div class="col-md-4">
          <% if employee.avatar.attached? %>
            <%= image_tag(employee.avatar.variant(:small), class: "img-fluid rounded-start") %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body" style="padding-bottom: 45px;">
            <div class="card-details">
              <h5 class="card-title"><%= "#{employee.job} - #{employee.name}" %></h5>
              <p><span class="bi-telephone card-icon"></span><%= employee.contact_number %></p>
              <p><span class="bi-envelope card-icon"></span><%= employee.email %></p>
              <p><strong>Introduction</strong></p>
              <p><%= employee.introduction %></p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-actions">
        <div class="btn-group float-end" role="group">
          <%= button_to "Edit", edit_employee_path(employee), class: "btn btn-primary btn-sm float-end", form: {style: 'margin-right: 5px'}, method: :get  %>
          <%= button_to "Destroy", employee_path(employee),
                          class: "btn btn-danger btn-sm float-end",
                          method: :delete,
                          remote: true,
                          data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render "form", employee: @employee %>