config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'dashboard#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/:adapter/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy'

  resources :contacts
  resources :leads do
    member do
      post :send_email
      post :book_appointment
      post :send_quotation
      get :installation_email
      get :quotation_email
      post :invoice
    end
  end
  resources :employees
  resources :products
  resources :translations, except: [:show]
end

app/controllers/leads_controller.rb
# frozen_string_literal: true

class LeadsController < ApplicationController
  before_action :authenticate_calendar_client_user, only: :book_appointment
  before_action :authenticate_accounts_client_user, only: :invoice
  before_action :set_lead, except: :index
  before_action :set_installer, except: :index

  def index
    @session_details = session[:zoho]

    return unless params[:search]&.present?

    @leads = crm_client.leads(email: params[:search])

    flash.now[:alert] = 'No leads could be found by matching the email you provided' if @leads.empty?
  end

  def show
    @errors = []

    @errors << "Installer #{@lead.installed_by} not found" if @installer.nil?
  end

  def book_appointment
    Time.zone = @installer.time_zone

    set_start_time

    @appointment = InstallationAppointment.build_new(
      employee: @installer,
      lead: @lead,
      start_time: @start_time,
      end_time: @start_time + params[:appointment_duration].to_i.hours
    )

    sender = Employee.find_by_email(params[:email_from])

    if @appointment.save
      @appointment.send_customer_email(sender, @lead, params[:test])
      @appointment.send_survey_email(sender, @lead, params[:test])
      @appointment.add_to_calendar(calendar_client, @lead, params[:test])

      flash[:success] = 'Installation has succesfully been booked'

      redirect_to :leads
    else
      render :show
    end
  end

  def installation_email
    @employee = Employee.find_by_email(params[:email_from])

    Time.zone = @installer.time_zone

    set_start_time
    set_product

    render 'contact_mailer/installation_email'
  end

  def send_quotation
    Time.zone = @installer.time_zone

    @employee = Employee.find_by_email(params[:email_from])

    set_start_time
    set_product

    ContactMailer.with(
      from: params[:email_from],
      lead: @lead,
      installer: @installer,
      start_time: @start_time.to_s,
      employee: @employee,
      product: @product,
      test_mode: params[:test]
    ).quotation_email.deliver_later

    flash[:success] = 'The quotation email has been sent'

    redirect_to :leads
  end

  def quotation_email
    @employee = Employee.find_by_email(params[:email_from])

    Time.zone = @installer.time_zone

    set_start_time
    set_product

    render 'contact_mailer/quotation_email'
  end

  def invoice
    opts = {
      name: @lead.full_name,
      email: @lead.email,
      phone_number: @lead.phone_number,
      address: @lead.street,
      postcode: @lead.zip_code,
      city: @lead.city
    }

    customer = accounts_client.find_or_create_customer(opts)

    products = []
    quantity = 1

    @lead.products_purchased.each do |product|
      product = accounts_client.find_product(product)
      products << { product: product, quantity: quantity }
    end

    accounts_client.create_invoice(
      customer: customer,
      products: products,
      invoice_date: @lead.installation_date
    )
  end


  private

  def set_lead
    @lead = crm_client.find_lead_by_id(params[:id])
    render('errors/not_found', status: '404') and return if @lead.nil?
  end

  def set_installer
    @installer = Employee.find_by_lowercase_name(@lead.installed_by.downcase)
  end

  def set_product
    @product = Product.find_by_lowercase_name(@lead.water_softener_model.downcase)
  end

  def set_start_time
    year, month, day = @lead.installation_date.split('-').map(&:to_i)
    @start_time = Time.zone.local(year, month, day, *params[:start_time].split(':').map(&:to_i))
  end
end

app/views/leads/index.html.erb
<div class="central-items">
  <h1>Leads Search</h1>

  <%= form_tag leads_path, method: :get do %>
    <div class="input-group mb-3">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Email" %>
    
      <%= submit_tag('Find Lead', name: nil, class: "btn btn-primary")  %>
    </div>
  <% end %>

  <% if @leads.present? %>
    <table class="table">
      <tr>
        <th>Full Name</th>
        <th>Email</th>
        <th>Link</th>
      </tr>
      <% @leads.each do |l| %>
        <tr>
          <td><%= l.full_name %></td>
          <td><%= l.email %></td>
          <td><%= button_to "Show Lead", lead_path(l.id), method: :get, class: "btn btn-primary float-end" %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/leads/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-7">
      <h1>Lead</h1>
    </div>

    <div class="col-sm-5" style="position: relative;">
      <%= link_to(
          'Open in CRM',
          @lead.link_address,
          target: "_blank",
          class: "btn btn-sm btn-success",
          style: "position: absolute; bottom: 8px; right: 10px;"
        )
      %>
    </div>
  </div>

  <hr/>

  <div class="row">
    <div class="col-sm-6">

      <table class="table">
        <tr>
          <th>Full Name</th>
          <td><%= @lead.full_name %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @lead.email %></td>
        </tr>
        <tr>
          <th>Water Softener</th>
          <td><%= @lead.water_softener_model %></td>
        </tr>
        <tr>
          <th>Water Softener Warranty</th>
          <td><%= @lead.softener_warranty_details %></td>
        </tr>
        <tr>
          <th>Packs of Block Salt</th>
          <td><%= @lead.salt_quantity %></td>
        </tr>
        <tr>
          <th>Installation Type</th>
          <td><%= @lead.installation_type %></td>
        </tr>
        <tr>
          <th>Drinking Tap</th>
          <td><%= @lead.drinking_taps %></td>
        </tr>
        <tr>
          <th>Drinking Water Filter</th>
          <td><%= @lead.drinking_water_filter %></td>
        </tr>

        <tr>
          <th>To be installed by</th>
          <td><%= @lead.installed_by %></td>
        </tr>
      </table>
    </div>

    <div class="col-sm-6">
      <div data-controller="map" data-action="google-maps-callback@window->map#initializeMap" data-map-post-code-value="<%= @lead.zip_code %>">
        <div id="map" style="height: 400px; width: 100%; background: green;"</div>
      </div>
    </div>
  </div>

  <hr/>

  <div class="row">

      <h2>Installation Details</h2>

      <% if @appointment && @appointment.errors %>
        <div class="alert alert-danger" role="alert">
          <p>Unable to book installation due to the following errors:</p>
          <ul>
            <% @appointment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>Unable to book installation due to the following errors:</p>
          <ul>
            <% @errors.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @installer.present? %>

        <%= form_tag(book_appointment_lead_path) do -%>
          <%= hidden_field_tag 'id', @lead.id %>

          <div class="row">
            <%= label_tag(:start_time, 'Start Time', class: 'col-sm-3 col-form-label') %>
            <div class="col-sm-9">
              <%= time_field_tag "start_time", @installer.preferred_start_time.to_formatted_s(:time) %>
            </div>
          </div>

          <div class="row">
            <%= label_tag(:appointment_duration, 'Appointment Duration', class: 'col-sm-3 col-form-label') %>
            <div class="col-sm-9">
              <%= select_tag "appointment_duration", options_for_select(1..24, 4), class: 'form-select form-select-lg mb-3' %>
            </div>
          </div>

          <div class="row">
            <%= label_tag(:email_from, 'Email From', class: 'col-sm-3 col-form-label') %>
            <div class="col-sm-9">
              <%=
                select_tag "email_from",
                options_for_select(Employee.internal.pluck(:email), ENV.fetch('EMAIL_DEFAULT_FROM_ADDRESS')),
                class: 'form-select form-select-lg mb-3'
              %>
            </div>
          </div>

          <div class="row">
            <%= label_tag(:test, 'Run Test', class: 'col-sm-3 col-form-label') %>
            <div class="col-sm-9">
              <%= check_box_tag 'test', 'yes', true %>
            </div>
          </div>

          <hr/>

          <h2>Actions</h2>

          <div class="row">
            <h4>Quotation</h4>
            <div class="col-sm-6">
              <div><%= submit_tag 'Preview Quotation Email', class: "btn btn-primary", formaction: quotation_email_lead_path, formmethod: :get %></div>
            </div>
            <div class="col-sm-4">
              <div><%= submit_tag 'Send Quotation', class: "btn btn-success", formaction: send_quotation_lead_path %></div>
            </div>
          </div>

          <h4>Book Installation</h4>

          <div class="row">
            <div class="col-sm-6">
              <div><%= submit_tag 'Preview Installation Email', class: "btn btn-primary", formaction: installation_email_lead_path, formmethod: :get %></div>
            </div>
            <div class="col-sm-6">
              <div><%= submit_tag 'Book Installation', class: "btn btn-success" %></div>
            </div>
          </div>

          <h4>Create Invoice</h4>

          <div class="row">
            <div class="col-sm-6">
              <div><%= submit_tag 'Create Invoice', class: "btn btn-primary", formaction: invoice_lead_path, formmethod: :post %></div>
            </div>
          </div>
        <% end %>

      <% end %>
  </div>
</div>