config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'dashboard#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/:adapter/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy'

  resources :contacts
  resources :leads do
    member do
      post :send_email
      post :book_appointment
      post :send_quotation
      get :installation_email
      get :quotation_email
      post :invoice
    end
  end
  resources :employees
  resources :products
  resources :translations, except: [:show]
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one_attached :main_photo do |attachable|
    attachable.variant :small, resize_to_limit: [400, 400]
    attachable.variant :medium, resize_to_limit: [600, 600]
  end
  has_one_attached :installed_photo  do |attachable|
    attachable.variant :small, resize_to_limit: [400, 400]
  end
  has_many_attached :other_photos

  validates :name, :record_type, presence: true

  def self.find_by_lowercase_name(name)
    where('lower(name) = ?', name.downcase).first
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all.order(created_at: :desc)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      respond_to do |format|
        format.html { redirect_to @product }
        format.turbo_stream
      end
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)

      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_path }
      format.turbo_stream
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :name, :record_type, :main_photo, :installed_photo, other_photos: []
    )
  end
end

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
	<div class="form-group">
		<%= form.label :name %>
		<%= form.text_area :name, class: "form-control" %>
		<% product.errors.full_messages_for(:name).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :record_type %>
		<%= form.select :record_type, ['water softener', 'tap'], {}, class: "form-select" %>
		<% product.errors.full_messages_for(:type).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :main_photo %>
		<%= form.file_field :main_photo, class: "form-control" %>
		<% product.errors.full_messages_for(:main_photo).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :installed_photo %>
		<%= form.file_field :installed_photo, class: "form-control" %>
		<% product.errors.full_messages_for(:installed_photo).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.label :other_photos %>
		<%= form.file_field :other_photos, multiple: true, class: "form-control" %>
		<% product.errors.full_messages_for(:other_photos).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.submit class: "btn btn-primary float-end" %>
	</div>
<% end %>

app/views/products/_new_product_button.html.erb
<%= turbo_frame_tag "product_button" do %>
	<div class="button-wrap">
		<%= button_to "New Product", new_product_path, class: "btn btn-primary", method: :get  %>
	</div>
<% end %>

app/views/products/_product.html.erb
<%= turbo_frame_tag product do %>
	<div class="card mb-3" id="product_<%= product.id %>">
		<%= link_to(product_path(product)) do %>
			<div class="row g-0">
				<div class="col-md-4">
					<% if product.main_photo.attached? %>
						<%= image_tag(product.main_photo.variant(:small), class: "img-fluid rounded-start") %>
					<% end %>
				</div>
				<div class="col-md-8">
					<div class="card-body" style="padding-bottom: 45px;">
						<div class="card-details">
							<h5 class="card-title"><%= product.name %></h5>
						</div>

					</div>
				</div>
			</div>
		<% end %>
		<div class="card-actions">
			<div class="btn-group float-end" role="group">
				<%= button_to "Edit", edit_product_path(product), class: "btn btn-primary btn-sm float-end", form: {style: 'margin-right: 5px'}, method: :get  %>
				<%= button_to "Destroy", product_path(product),
												class: "btn btn-danger btn-sm float-end",
												method: :delete
				%>
			</div>
		</div>
	</div>
<% end %>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.prepend "products", @product %>
<%= turbo_stream.remove Product.new %>
<%= turbo_stream.append "product_button", partial: "new_product_button" %>

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove @product %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="container-fluid">
  <h1>Products</h1>

  <hr/>

  <div class="row">

    <div class="col-sm-7">
      <%= turbo_frame_tag "products" do %>
        <%= render @products %>
      <% end %>
    </div>

    <div class="col-sm-5">
      <%= turbo_frame_tag "product_button" do %>
        <%= render partial: "new_product_button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= turbo_frame_tag 'product_button' do %>
  <%= render "form", product: @product %>
<% end %>

app/views/products/show.html.erb
<h1>Product</h1>

<p>Name: <%= @product.name %></p>
<p>Type: <%= @product.record_type %></p>

<p>Main Photo</p>

<% if @product.main_photo.present? %>
  <div>
    <%= image_tag(@product.main_photo.variant(:small)) %>
  </div>
<% end %>

<p>Installed Photo</p>

<% if @product.installed_photo.present? %>
  <div>
    <%= image_tag(@product.installed_photo.variant(:small)) %>
  </div>
<% end %>

<% if @product.other_photos_attachments %>
  <p>Photos:</p>
  <div>
    <% @product.other_photos_attachments.each do |photo| %>
      <%= image_tag(photo.variant(:small)) %>
    <% end %>
  </div>
<% end %>

<ul>
  <li><%= link_to "Edit", edit_product_path(@product) %></li>
  <li><%= link_to "Destroy", product_path(@product),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>