config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'dashboard#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/:adapter/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy'

  resources :contacts
  resources :leads do
    member do
      post :send_email
      post :book_appointment
      post :send_quotation
      get :installation_email
      get :quotation_email
      post :invoice
    end
  end
  resources :employees
  resources :products
  resources :translations, except: [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UkwsAdmin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV.fetch('GOOGLE_MAP_API_KEY')}&callback=dispatchMapsEvent", defer: true, async: true %>
  </head>

  <body class="application-layout-body">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <nav class="navbar navbar-dark company-blue">
      <div class="container-fluid">
        <%= link_to "UKWS", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="main-menu">
          <ul class="navbar-nav me-auto mb-2">
            <li class="nav-item">
              <%= link_to "Contacts", contacts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Leads", leads_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Employees", employees_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Products", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Translations", translations_path, class: "nav-link" %>
            </li>
            <% if active_user_session? %>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="application-layout-main">
      <div class="central-items">
        <%=  render "flash_messages" %>

        <%= yield %>
      </div>
      </div>
  </body>
</html>